### ISSUE TITLE
add things needed in the house to house section

### ISSUE THREAD

**Issue by CIEspost** [CIEspost/colab-shopping#1]

**Comment by zacck** [comment]
Hey do we have butter? we should probably add it to the list any other thing that you can think of

**Comment by CIEspost** [comment]
yes we have butter

**Comment by zacck** [comment]
What can we add to the house list?

**Comment by CIEspost** [comment]
custard

**Comment by zacck** [comment]
anything else?

**Comment by CIEspost** [comment]
nothing

**Comment by zacck** [comment]
ok then I will quickly add the  custard

**Comment by CIEspost** [comment]
![huis 2](https://user-images.githubusercontent.com/19358273/45345671-4e24ca80-b5a7-11e8-944b-97b304ec1b35.jpg)
